version: '1.0'

services:
  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=app
    networks:
      - my-app-network
    ports:
      - "27017:27017"
    restart: always

  app:
    depends_on:
      - mongodb
    build:
      context: .
      dockerfile: Dockerfile
    image: frankester/todo-app
    restart: on-failure
    ports:
      - "8080:8080"
    environment:    
      - SPRING.DATA.MONGODB.URI=mongodb://mongodb:27017
      - SPRING.DATA.MONGODB.DATABASE=app
    networks:
      - my-app-network


networks:
  my-app-network:

